### PR TITLE
do not deparse length 1 named vector

### PR DESCRIPTION
**Pull request by philaris**
This fixes issue https://github.com/opencpu/opencpu/issues/412.

### CODE REVIEW

**Comment by jeroen** [comment]
Thank you

**Comment by jeroen** [comment]
Do you need this feature soon or is it mostly just for correctness?

**Comment by philaris** [comment]
> Do you need this feature soon or is it mostly just for correctness?

I would say it is mostly for correctness.

There is another border case in #414 which is fixed by #415.

Is there a reason you treat specially primitives as expressions at the end of function `parse_post`?

Another comment: As I read the code, I realized that you support `application/rds` in `parse_post`. However at https://www.opencpu.org/api.html in the "Argument formats for R function calls (HTTP POST only)" section, you do not mention rds as a possible format of POST data. What is the situation?

**Comment by jeroen** [comment]
> Is there a reason you treat specially primitives as expressions at the end of function parse_post?

IIRC that was to get cleaner function calls in the session history. For example if you do:

```sh
curl https://cloud.opencpu.org/ocpu/library/base/R/list/console -d 'foo=123' -d 'bar=true' -d 'baz=iris'
```

The function call that is stored shows:

```r
> list(foo = 123, bar = TRUE, baz = iris)
```

And not `list(foo = foo, bar = bar, baz = iris)`

**Pull request merged**
