### PR TITLE
Compatibility with devtools::load_all

### PR DESCRIPTION
**Pull request by assaron**
Hi,

I'm developing an R package that is used via opencpu. In that process I've struggled a lot with requirement of reinstalling the package each time I made a change to check how it works. Normally I use devtools::load_all for quick loading and testing, however it is incompatible with opencpu, as opencpu uses only packages from .libPaths(). I suggest to use default NULL values, which allows using loaded packages not only the ones that are installed in the library.

With this patch I can quickly run opencpu with updated package with a command `R -e "devtools::load_all();  opencpu::opencpu$start(8000)".

### CODE REVIEW

**Comment by jeroen** [comment]
Hi I'll look into this. Note that the `opencpu::opencpu$start(8000)` api has changed in version 2.0 to `opencpu::ocpu_start_server(8000)`.

**Comment by assaron** [comment]
Thanks!

**Comment by jeroen** [comment]
I this this is not a good solution because for example [listing packages will break]( https://github.com/opencpu/opencpu/blob/master/R/httpget_library.R#L12). Perhaps we can just check if the package has already been loaded? Or we might need a new endpoint `/ocpu/dev` or so. I never use `devtools::load_all()` so I'm not sure what it does.

**Comment by assaron** [comment]
I checked what's going on. Basically, what load_all does is to create a namespace and loads it into the session. If you look at how `bas::find.packages` is implemented you can see, that if `lib.loc` is set to NULL, then it also look inside loaded namespaces. 

I made a corresponding commit that fixes library listing, but I'm not sure whether other places do support setting lib.loc to NULL.

**Comment by jeroen** [comment]
The problem is also that `load_all` does not seem to copy files from `./inst`. So you can't use it to test apps I suppose? How do you use this?

**Comment by assaron** [comment]
Right, it does not copy `inst` directory, but it sets the package path properly, so `inst` is available. For example, I have a package called `phantasus` in `~/workspace/phantasus` directory. I load it using `devtools::load_all("~/workspace/phantasus")`, the if I run `find.package("phantasus")` it will return `"~/workspace/phantasus"`. `data()` function is also compatible with this, and there is a wrapper provided for `system.file()`.

**Comment by assaron** [comment]
Hi, any updates?

**Comment by dan-reznik** [comment]
i have the sense across the board the conversion between json's NULL (at a GET or POST) <-> R's NA (as passed to a pkg's function) is not being respected.

**Comment by assaron** [comment]
I'm still interested in getting this feature into upstream. It saves me a lot of time to be able to quickly reload my package in opencpu instance without reinstalling the package each time.

Is there anything I can do to make it merged?

**Comment by jeroen** [comment]
I'm worried about the side effects that `loadedNamespaces()` may have in the server environment. So is the main goal here to make the default `lib.loc` parameter in `find.package()` to be `NULL`?

**Comment by assaron** [comment]
> So is the main goal here to make the default lib.loc parameter in find.package() to be NULL?

Yes.

> I'm worried about the side effects that loadedNamespaces() may have in the server environment.

Well, I don't see it used in the deployed server environment. I personally use it in interactive mode: save the package updated code, interrupt the server, and run it with the R load_all + ocpu_start_server command. 

Could it be an option in the server command (like devMode=T/F or something)? Will it resolve your worries?

**Comment by jeroen** [comment]
No I think it's fine. It probably makes sense to first check loaded namespaces.

Your use of `unique(packages)` has no effect in this case but I'll rewrite it anyway.

**Comment by assaron** [comment]
Thank you!

**Pull request merged**
