### PR TITLE
Bitbucket integration added.

### PR DESCRIPTION
**Pull request by moosilauke18**
Added ability to install bitbucket repos by adding `bitbucket_username` and `bitbucket_password` to the secret.conf file.

### CODE REVIEW

**Comment by moosilauke18** [comment]
@jeroenooms Any word on this pull request?

**Comment by jeroenooms** [comment]
I'm sorry I've been swamped with other work. I'll try to review this soon. Thanks :)

**Comment by znmeb** [comment]
Let me know if you need a BitBucket tester - I have a bunch of repos there.

**Comment by jeroen** [comment]
Closing in favor of https://github.com/opencpu/opencpu/issues/238.

**Pull request closed without merging**
