### PR TITLE
support feather2 and arrowipc

### LINKED ISSUE #395: add more recent "arrow" format for outputs ?
It seems that the "feather" format opencpu support for outputs is rather deprecated.
(at least the version which is produced bye feather::write_feather)
I think opencpu should add an other format of  the "arrow" family as a output format.

### PR DESCRIPTION
**Pull request by behrica**
fixes #395 

I can change docu as well, if you agree on the PR

### CODE REVIEW

**Comment by jeroen** [comment]
Actually maybe we should just replace the old `feather` such that we can drop the feather dependency?

**Comment by jeroen** [comment]
I've changed it, and also added the parquet format. 

However do note that the opencpu cloud server is built on ubuntu public build servers, which disable internet access. So the R package is built in it's bare minimal form:

```
*** Building C++ library from source, but downloading thirdparty dependencies
    is not possible, so this build will turn off all thirdparty features.
    See install vignette for details:
```

**Comment by behrica** [comment]
> Actually maybe we should just replace the old `feather` such that we can drop the feather dependency?

I investigated this a bit.
The current endpoints
"feather"
"feather2"
"arrow"

produce indeed three different files.
Sometimes they are called "feather v1", "feather v2" and "arrow"
But this is wording is a bit confusing and not consistent.

**Comment by behrica** [comment]
But it seems indeed that "arrow" package can write as well the "feather v1" format.
So we could indeed use `arrow::write_feather(iris,"/tmp/iris.feather",version=1)` instead of `feather::write_feather`

**Comment by behrica** [comment]
I think your last commit broke backwards compatibility of opencpu

endpoint "/feather" will know write "feather v2", while before it wrote "feather v1"

**Comment by jeroen** [comment]
> I think your last commit broke backwards compatibility of opencpu
> endpoint "/feather" will now write "feather v2", while before it wrote "feather v1"

That's fine, I don't think anyone was really using this, I added this format more of as an experiment. As you say it is deprecated so might as well bump to the new version.

The production containers in opencpu are tagged by version, so if anyone really needs feather-v1 they can keep running a previous build of opencpu.

**Comment by jeroen** [comment]
Note that opencpu by design allows you to pass parameters to the format function. So you can do:

 - https://cloud.opencpu.org/ocpu/library/MASS/data/cats/feather
 - https://cloud.opencpu.org/ocpu/library/MASS/data/cats/feather?version=1

**Comment by behrica** [comment]
> 

Ok, thats fine.

**Pull request merged**
